import 'package:flutter/material.dart';

class Product {
  final String title;
  final String image;
  final String review;
  final String seller;
  final double price;
  final List<Color> colors;
  final String category;
  final double rate;
  int quantity;

  Product(
      {required this.title,
      required this.review,
      required this.image,
      required this.price,
      required this.colors,
      required this.seller,
      required this.category,
      required this.rate,
      required this.quantity});
}

//Semua
final List<Product> all = [
  Product(
    title: "Wireless",
    image: "images/all/wireless.png",
    price: 270000,
    seller: "Trend Mall",
    colors: [
      Colors.black,
      Colors.blue,
      Colors.orange,
    ],
    category: "Electronics",
    review: "(320 Reviews)",
    rate: 4.8,
    quantity: 1,
  ),
  Product(
    title: "Woman Sweter",
    image: "images/all/sweet.png",
    price: 122000,
    seller: "Trend Mall",
    colors: [
      Colors.brown,
      Colors.deepPurple,
      Colors.pink,
    ],
    category: "Woman Fashion",
    review: "(32 Reviews)",
    rate: 4.5,
    quantity: 1,
  ),
  Product(
    title: "Smart Watch",
    image: "images/all/miband.jpg",
    price: 630000,
    seller: "Trend Mall",
    colors: [
      Colors.black,
      Colors.amber,
      Colors.purple,
    ],
    category: "Electronics",
    review: "(20 Reviews)",
    rate: 4.0,
    quantity: 1,
  ),
  Product(
    title: "Mens Jacket",
    image: "images/all/jacket.png",
    price: 349999,
    seller: "Trend Mall",
    colors: [
      Colors.blueAccent,
      Colors.orange,
      Colors.green,
    ],
    category: "Men Fashion",
    review: "(20 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
];

//Sepatu Pria
final List<Product> menshoes = [
  Product(
    title: "Porsehc 1987 casual",
    image: "images/men shoes/1.jpg",
    price: 340999,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "D'Lux Journey sneakers",
    image: "images/men shoes/2.jpg",
    price: 1299000,
    seller: "Trend Mall",
    colors: [
      Colors.blueAccent,
      Colors.blueGrey,
      Colors.green,
    ],
    category: "Men's Shoes",
    review: "(200 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Bouder 2.0 sneakers",
    image: "images/men shoes/3.jpg",
    price: 1099000,
    seller: "Trend Mall",
    colors: [
      Colors.red,
      Colors.orange,
      Colors.greenAccent,
    ],
    category: "Men's Shoes",
    review: "(100 Reviews)",
    rate: 4.8,
    quantity: 1,
  ),
  Product(
    title: "Go Run Elevate Sneakers",
    image: "images/men shoes/4.jpg",
    price: 956000,
    seller: "Trend Mall",
    colors: [
      Colors.deepPurpleAccent,
      Colors.orange,
      Colors.green,
    ],
    category: "Men's Shoes",
    review: "(60 Reviews)",
    rate: 3.0,
    quantity: 1,
  ),
  Product(
    title: "Hillcrest Men's Sneakers",
    image: "images/men shoes/5.jpg",
    price: 999000,
    seller: "Trend Mall",
    colors: [
      Colors.blueAccent,
      Colors.orange,
      Colors.green,
    ],
    category: "Men's Shoes",
    review: "(00 Reviews)",
    rate: 0.0,
    quantity: 1,
  ),
  Product(
    title: "Go Run Elevate Sneakers",
    image: "images/men shoes/6.jpg",
    price: 1199000,
    seller: "Trend Mall",
    colors: [
      Colors.blueAccent,
      Colors.orange,
      Colors.green,
    ],
    category: "Men's Shoes",
    review: "(00 Reviews)",
    rate: 0.0,
    quantity: 1,
  ),
  Product(
    title: "Uno Court Sneakers",
    image: "images/men shoes/7.jpg",
    price: 1199200,
    seller: "Trend Mall",
    colors: [
      Colors.blueAccent,
      Colors.orange,
      Colors.green,
    ],
    category: "Men's Shoes",
    review: "(00 Reviews)",
    rate: 0.0,
    quantity: 1,
  ),
  Product(
    title: "D'Lux Journey Sneakers",
    image: "images/men shoes/8.jpg",
    price: 1299000,
    seller: "Trend Mall",
    colors: [
      Colors.blueAccent,
      Colors.orange,
      Colors.green,
    ],
    category: "Men's Shoes",
    review: "(00 Reviews)",
    rate: 0.0,
    quantity: 1,
  ),
  Product(
    title: "Slip-Ins Summits",
    image: "images/men shoes/9.jpg",
    price: 1199000,
    seller: "Trend Mall",
    colors: [
      Colors.blueAccent,
      Colors.orange,
      Colors.green,
    ],
    category: "Men's Shoes",
    review: "(00 Reviews)",
    rate: 0.0,
    quantity: 1,
  ),
  Product(
    title: "New Wave Cup Shoes",
    image: "images/men shoes/10.jpg",
    price: 1499000,
    seller: "Trend Mall",
    colors: [
      Colors.blueAccent,
      Colors.orange,
      Colors.green,
    ],
    category: "Men's Shoes",
    review: "(00 Reviews)",
    rate: 0.0,
    quantity: 1,
  ),
];

//Sepatu Wanita
final List<Product> womenshoes = [
  Product(
    title: "Uno Women's Leisure",
    image: "images/women shoes/1.jpg",
    price: 1199000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "D'Lux Walker Women's",
    image: "images/women shoes/2.jpg",
    price: 999000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "A Linear Women's",
    image: "images/women shoes/3.jpg",
    price: 1199200,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Bobs B Flex Hi",
    image: "images/women shoes/4.jpg",
    price: 1099000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Glide Step Sport",
    image: "images/women shoes/5.jpg",
    price: 1199000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Squad Chaos Sr",
    image: "images/women shoes/6.jpg",
    price: 959000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Go Run consistent 2.0",
    image: "images/women shoes/7.jpg",
    price: 959000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Skech Air Court",
    image: "images/women shoes/8.jpg",
    price: 1099000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Slip-Ins Ultra Flex",
    image: "images/women shoes/9.jpg",
    price: 1299000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Go Run Pulse 2.0",
    image: "images/women shoes/10.jpg",
    price: 879200,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Shoes",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
];

//Pakaian Wanita
final List<Product> womenfashion = [
  Product(
    title: "Agata Blouse Atasan",
    image: "images/women fashion/1.jpeg",
    price: 158900,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Baju atasan Lengan Panjang",
    image: "images/women fashion/2.jpeg",
    price: 149000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "frily Tunik",
    image: "images/women fashion/3.jpeg",
    price: 68900,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Idon't care Permpuan",
    image: "images/women fashion/4.jpg",
    price: 47000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Ks58 Perempuan",
    image: "images/women fashion/5.jpg",
    price: 65000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Ks67 Perempuan",
    image: "images/women fashion/6.jpg",
    price: 68000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Hello Ks125 Permpuan",
    image: "images/women fashion/7.jpg",
    price: 85000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Always Together Ks335",
    image: "images/women fashion/8.jpg",
    price: 67000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Iam Groot Ks235",
    image: "images/women fashion/9.jpg",
    price: 64000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Simple Pleasure Ks67",
    image: "images/women fashion/10.jpg",
    price: 66000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Women's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
];

//Pakaian Pria
final List<Product> menfashion = [
  Product(
    title: "Cardinal Jeans",
    image: "images/men fashion/1.jpg",
    price: 110000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos the end black",
    image: "images/men fashion/2.jpg",
    price: 99000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos New balance blue",
    image: "images/men fashion/3.jpg",
    price: 127000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Fighter Mobile legends",
    image: "images/men fashion/4.jpg",
    price: 49000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Distro One piece",
    image: "images/men fashion/5.jpeg",
    price: 59000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Kaos Distro Squirdward",
    image: "images/men fashion/6.jpg",
    price: 57000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Woopie Project",
    image: "images/men fashion/7.jpeg",
    price: 97500,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Trip To Surf",
    image: "images/men fashion/8.jpeg",
    price: 96000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Bamboo Trip Now Think Later",
    image: "images/men fashion/9.jpeg",
    price: 95000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
  Product(
    title: "Summer Vacation",
    image: "images/men fashion/10.jpeg",
    price: 98000,
    seller: "Trend Mall",
    colors: [
      Colors.grey,
      Colors.amber,
      Colors.purple,
    ],
    category: "Men's Fashion",
    review: "(55 Reviews)",
    rate: 5.0,
    quantity: 1,
  ),
];
